formatter: "markdown"

recursive:
  enabled: true
  path: modules

sections:
  show:
    - providers
    - resources
    - inputs
    - outputs

output:
  file: "README.md"
  mode: append

sort:
  enabled: true
  by: required

settings:
  color: true
  hide-empty: true
