name: Generate terraform docs
on:
  - push
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.0"
      - run: go install github.com/terraform-docs/terraform-docs@v0.17.0
      - run: $(go env GOPATH)/bin/terraform-docs markdown -c .terraform-docs.yml .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "👻 (Module READMEs): Automated Terraform Documentation"
